---
- hosts: all
  become: yes
  tasks:
    - name: install docker
      apt:
        name: docker.io
        force_apt_get: yes

    - name: start and enable docker.service
      systemd:
        name: docker.service
        state: started
        enabled: yes

    - name: install pip
      apt:
        name: python3-pip
        force_apt_get: yes

    - name: upgrade pip
      pip:
        name: pip
        version: 19.2.2

    - name: install pip modules
      pip:
        name:
          - docker
          - docker-compose
          - pyyaml
