---
- hosts: all
  become: yes
  tasks:
    - name: set timezone to UTC
      timezone:
        name: UTC

    - name: install ntp
      apt:
        name: ntp
        force_apt_get: yes
    
    - name: start and enable ntp.service
      systemd:
        name: ntp.service
        state: started
        enabled: yes
