- name: create prometheus installation directories
  file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - /opt/prometheus
    - /opt/prometheus/rules
    - /opt/prometheus/data

- name: create prometheus configuration file
  template:
    src: prometheus.yml.j2
    dest: /opt/prometheus/prometheus.yml
    owner: root
    group: root
    mode: 0644
  notify: restart prometheus

- name: create docker alerting rules
  template:
    src: rules_docker.yml.j2
    dest: /opt/prometheus/rules/rules_docker.yml
    owner: root
    group: root
    mode: 0644
  notify: restart prometheus

- name: create prometheus container
  docker_container:
    name: prometheus
    image: prom/prometheus:v2.7.1
    state: started
    restart_policy: always
    network_mode: host
    user: root
    volumes:
      - /opt/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /opt/prometheus/rules:/etc/prometheus/rules
      - /opt/prometheus/data:/prometheus
