vms = [
    { 'name' => 'mag1.site1.region1.egfast.com', 'ip' => '192.168.42.100' },
    { 'name' => 'app1.site1.region1.egfast.com', 'ip' => '192.168.42.101' },
]

Vagrant.configure('2') do |config|
    config.vm.box = 'bento/ubuntu-18.04'
    config.ssh.insert_key = false
    vms.each do |host|
        config.vm.define host['name'] do |t|
            t.vm.hostname = host['name']
            t.vm.network(:private_network, ip: host['ip'])
            t.vm.provider 'virtualbox' do |v|
              v.memory = host['memory'] || 4096
            end
        end
    end
end
